name = "MultipathChannel"
uuid = "a0de0523-4880-46e2-8f2e-e01f2b1f4520"
authors = ["hassiweb <nryk.hashimoto@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
